initial dpp dataproducts
ioxio-dataspace/sandbox-definitions pull request #49
Opened 2023-09-26 07:06 UTC by belham

First version of the Dataproducts for DPP

2023-09-26 07:16 UTC, lietu commented
We just discussed that the folder should not be called `DPP` but `DigitalProductPassports`

2023-10-02 07:29 UTC, hsuomi requested changes

2023-10-02 07:29 UTC, hsuomi commented on DataProducts/DPP/Energy/Battery/LastChargeEntry_v0.1.json
> +{
For simplicity for now let's leave the Energy out of the path now for simplicity. We do not have that many product categories coming so let's leave the upper level ontology out for now.

So I would suggest these for the paths for the first DPP products

DigitalProductPassport/Battery/DataSheet
DigitalProductPassport/Battery/Manufacturing/EnvironmentalFootprint
DigitalProductPassport/Battery/UsageHistory

2023-10-02 07:29 UTC, hsuomi commented on DataProducts/DPP/Energy/Battery/LastChargeEntry_v0.1.json
> +        "description": "Information about latest charge cycle of a battery",
This is actually a bit wider than what the description has said earlier. I would widen this into "Information about the use of the battery" to describe the contents better

2024-04-25 07:14 UTC, closed without merging