Manufacturing dataproducts
ioxio-dataspace/sandbox-definitions pull request #53
Opened 2023-12-11 22:07 UTC by omarudolley

Implementation of the Manufacturing dataproducts definitions

2023-12-19 09:42 UTC, joakimnordling commented on src/DigitalProductPassport/Battery/ManufacturingDataSheet_v0.1.py
> +    legal_conformity: LegalConformity = Field(
`extinguishing_agent` was not supposed to be removed altogether, just changed to a list of strings.

2023-12-19 09:56 UTC, joakimnordling commented on src/DigitalProductPassport/Battery/HealthData_v0.1.py
> +        description="The periodic information of he battery operation",
```suggestion
        description="The periodic information of the battery operation",
```

2023-12-19 10:04 UTC, joakimnordling commented on src/DigitalProductPassport/Battery/HealthData_v0.1.py
> +    date: Optional[datetime] = Field(
This should be a date, not a datetime.

2023-12-19 10:04 UTC, joakimnordling commented on src/DigitalProductPassport/Battery/HealthData_v0.1.py
> +    date: datetime = Field(
This should be a date, not a datetime.

2023-12-19 10:08 UTC, joakimnordling commented on src/DigitalProductPassport/MovableWorkMachine/EnvironmentalFootprint_v0.1.py
Supposed to be in MobileWorkMachine, not MovableWorkMachine

2023-12-22 11:01 UTC, joakimnordling commented on src/DigitalProductPassport/Battery/HealthData_v0.1.py
> +    date: Optional[datetime] = Field(
This one should as well be a date, not a datetime.

2023-12-22 11:17 UTC, joakimnordling reviewed
Apart from the fields that should be dates and not dates this looks good to me. There's however some issue with the tooling (openapi-to-fastapi and validation there) that causes issues for the pre-commit hooks if the fields are changed to dates, so this will require a bit of investigation of the issues with that tooling.

2024-01-03 09:01 UTC, joakimnordling commented on src/DigitalProductPassport/Battery/HealthData_v0.1.py
> +from pydantic import EmailStr, Field
`EmailStr` is not used in this definition.

2024-01-04 14:15 UTC, joakimnordling commented on src/DigitalProductPassport/Battery/HealthData_v0.1.py
> +    date: Optional[datetime] = Field(
Renamed this one as well.

2024-01-04 14:17 UTC, joakimnordling approved these changes

2024-01-12 13:00 UTC, hsuomi requested changes

2024-01-15 06:42 UTC, hsuomi approved these changes

2024-01-15 06:46 UTC, merged